(function(){
let IMPORT_ROWS=[];
function normHeader(v){return String(v||'').trim().replace(/\s+/g,' ').replace(/[ـ]/g,'')}
function valueOf(row,names){for(const n of names){const key=Object.keys(row).find(k=>normHeader(k)===n);if(key!==undefined)return String(row[key]??'').trim()}return''}
function digits(v){return String(v??'').replace(/[٠-٩]/g,d=>'0123456789'['٠١٢٣٤٥٦٧٨٩'.indexOf(d)]).replace(/[۰-۹]/g,d=>'0123456789'['۰۱۲۳۴۵۶۷۸۹'.indexOf(d)]).replace(/\D/g,'')}
function saudiMobile(v){let n=digits(v);if(n.startsWith('00966'))n=n.slice(2);if(n.startsWith('9660'))n='966'+n.slice(4);if(n.startsWith('05')&&n.length===10)n='966'+n.slice(1);else if(n.startsWith('5')&&n.length===9)n='966'+n;return /^9665\d{8}$/.test(n)?n:''}
function localMobile(v){const n=saudiMobile(v);return n?'0'+n.slice(3):''}
function autoPriority(category,address){const c=String(category||'').toLowerCase(),a=String(address||'').toLowerCase();const target=['كمبيوتر','حاسب','جوال','اتصالات','إلكترون','الكترون','تقنية','أجهزة ذكية','اجهزة ذكية','اكسسوار','إكسسوار','صيانة'].some(k=>c.includes(k));const hot=['فلسطين','خالد بن الوليد','مدينة الكمبيوتر','مجمع الأمير','مركز الأمير','جوال مول','الصانع مول'].some(k=>a.includes(k));const low=['قرطاسية','مكتبة','خدمات طلابية','طباعة','تصوير'].some(k=>c.includes(k));if(target&&hot)return'A';if(target)return'B';if(low)return'C';return hot?'B':'C'}
function escI(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function panelHTML(){return `<div class=panel id=excelImportPanel><div class=n>استيراد العملاء من Excel</div><div class=m>أعمدة الملف: اسم المحل — التصنيف — العنوان — رقم الجوال. يقبل النظام أرقام الجوال السعودية فقط، ويتم تحديد الأولوية A/B/C تلقائيًا.</div><input id=customerExcelFile type=file accept=".xlsx,.xls"><div class=pa><button class=blue onclick="previewCustomerExcel()">قراءة ومعاينة الملف</button><button id=confirmExcelImport class=excel style="display:none" onclick="confirmCustomerExcelImport()">إضافة العملاء</button></div><div id=importExcelMsg class=ok></div><div id=importExcelPreview style="overflow:auto"></div></div>`}
function installPanel(){const panels=[...document.querySelectorAll('.panel')],add=panels.find(x=>x.textContent.includes('إضافة عميل جديد'));if(add&&!document.getElementById('excelImportPanel'))add.insertAdjacentHTML('beforebegin',panelHTML())}
function renumberCustomers(){const cards=[...document.querySelectorAll('#l .c')];cards.forEach((card,i)=>{const title=card.querySelector('.n');if(title)title.innerHTML=title.innerHTML.replace(/^#\d+\s*/,`#${i+1} `)})}
function installRenumber(){const list=document.getElementById('l');if(!list)return;renumberCustomers();new MutationObserver(()=>renumberCustomers()).observe(list,{childList:true})}
function restrictPhoneInput(el){if(!el)return;el.setAttribute('inputmode','numeric');el.setAttribute('maxlength','10');el.setAttribute('pattern','05[0-9]{8}');el.setAttribute('placeholder','رقم الجوال السعودي 05XXXXXXXX');el.addEventListener('input',()=>{let n=digits(el.value);if(n.startsWith('9665'))n='0'+n.slice(3);else if(n.startsWith('5')&&n.length<=9)n='0'+n;el.value=n.slice(0,10)})}
function installSaudiValidation(){restrictPhoneInput(document.getElementById('cp'));restrictPhoneInput(document.getElementById('ep'));const oldAdd=window.addCustomer;window.addCustomer=function(){const el=document.getElementById('cp'),ok=document.getElementById('addok');if(!saudiMobile(el.value)){ok.textContent='يجب إدخال رقم جوال سعودي صحيح يبدأ بـ 05 ويتكون من 10 أرقام.';return}el.value=localMobile(el.value);return oldAdd()};const oldSave=window.saveEdit;window.saveEdit=function(){const el=document.getElementById('ep'),ok=document.getElementById('editok');if(!saudiMobile(el.value)){ok.textContent='يجب إدخال رقم جوال سعودي صحيح يبدأ بـ 05 ويتكون من 10 أرقام.';return}el.value=localMobile(el.value);return oldSave()}}
function loadPWA(){const old=document.getElementById('slbPwaScript');if(old)old.remove();const s=document.createElement('script');s.id='slbPwaScript';s.src='pwa.js?v=4';document.head.appendChild(s)}
window.previewCustomerExcel=async function(){const f=document.getElementById('customerExcelFile').files[0],msg=document.getElementById('importExcelMsg'),box=document.getElementById('importExcelPreview'),btn=document.getElementById('confirmExcelImport');IMPORT_ROWS=[];btn.style.display='none';box.innerHTML='';if(!f){msg.textContent='اختر ملف Excel أولًا.';return}if(typeof ExcelJS==='undefined'){msg.textContent='تعذر تحميل أداة Excel. تأكد من اتصال الإنترنت.';return}try{const wb=new ExcelJS.Workbook();await wb.xlsx.load(await f.arrayBuffer());const ws=wb.worksheets[0];if(!ws){msg.textContent='ملف Excel لا يحتوي على ورقة بيانات.';return}const headers={};ws.getRow(1).eachCell((cell,col)=>headers[col]=normHeader(cell.text));const required=['اسم المحل','التصنيف','العنوان','رقم الجوال'];const missing=required.filter(h=>!Object.values(headers).includes(h));if(missing.length){msg.textContent='الأعمدة الناقصة: '+missing.join('، ');return}ws.eachRow((row,num)=>{if(num===1)return;const obj={};row.eachCell({includeEmpty:true},(cell,col)=>obj[headers[col]]=cell.text);const name=valueOf(obj,['اسم المحل']),category=valueOf(obj,['التصنيف']),address=valueOf(obj,['العنوان']),phone=valueOf(obj,['رقم الجوال']);if(!name&&!phone&&!address)return;const normalized=saudiMobile(phone);IMPORT_ROWS.push({name,category:category||'غير محدد',address,phone:localMobile(phone),normalized,priority:autoPriority(category,address),valid:!!(name&&address&&normalized)})});if(!IMPORT_ROWS.length){msg.textContent='لم يتم العثور على عملاء في الملف.';return}const existing=new Set(all().map(x=>saudiMobile(x[2])).filter(Boolean)),seen=new Set();let dup=0,bad=0,ready=0;IMPORT_ROWS.forEach(x=>{x.duplicate=!x.valid||existing.has(x.normalized)||seen.has(x.normalized);if(!x.valid)bad++;else if(x.duplicate)dup++;else{seen.add(x.normalized);ready++}});msg.textContent=`تمت قراءة ${IMPORT_ROWS.length} سجل — جاهز للإضافة: ${ready} — مكرر: ${dup} — رقم/سجل غير صالح: ${bad}.`;btn.style.display=ready?'inline-block':'none';box.innerHTML=`<table style="width:100%;border-collapse:collapse;margin-top:10px;font-size:13px"><thead><tr><th>اسم المحل</th><th>التصنيف</th><th>العنوان</th><th>الجوال</th><th>الأولوية</th><th>الحالة</th></tr></thead><tbody>${IMPORT_ROWS.map(x=>`<tr style="opacity:${x.duplicate?.55:1}"><td>${escI(x.name)}</td><td>${escI(x.category)}</td><td>${escI(x.address)}</td><td>${escI(x.phone)}</td><td><b>${x.priority}</b></td><td>${!x.valid?'رقم/سجل غير صالح':x.duplicate?'مكرر':'جاهز'}</td></tr>`).join('')}</tbody></table>`;[...box.querySelectorAll('th,td')].forEach(e=>{e.style.borderBottom='1px solid #e5e7eb';e.style.padding='7px';e.style.textAlign='right'})}catch(e){console.error(e);msg.textContent='تعذرت قراءة الملف. استخدم ملف Excel بصيغة .xlsx وبالأعمدة المطلوبة.'}}
window.confirmCustomerExcelImport=function(){const msg=document.getElementById('importExcelMsg');if(!IMPORT_ROWS.length)return;const existing=new Set(all().map(x=>saudiMobile(x[2])).filter(Boolean)),seen=new Set(),ids=BASE.concat(CUSTOM).map(x=>x[0]);let next=Math.max(...ids,66)+1,added=0,duplicates=0,invalid=0;for(const x of IMPORT_ROWS){if(!x.valid){invalid++;continue}if(existing.has(x.normalized)||seen.has(x.normalized)){duplicates++;continue}CUSTOM.push([next++,x.name,x.phone,x.priority,x.address,x.category,'','']);seen.add(x.normalized);existing.add(x.normalized);added++}localStorage.slbCustomers=JSON.stringify(CUSTOM);r();msg.textContent=`تمت الإضافة بنجاح: ${added} عميل — لم تتم إضافة ${duplicates} بسبب التكرار${invalid?' — تم رفض '+invalid+' سجلًا لأن رقم الجوال غير سعودي أو البيانات ناقصة':''}.`;document.getElementById('confirmExcelImport').style.display='none';document.getElementById('customerExcelFile').value='';IMPORT_ROWS=[]}
function init(){installPanel();installRenumber();installSaudiValidation();loadPWA()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();