(function(){
const LOGO_DB='slbBrandDB',STORE='brand';
function installPWAHead(){let l=document.querySelector('link[rel="manifest"]');if(!l){l=document.createElement('link');l.rel='manifest';document.head.appendChild(l)}l.href='./manifest.webmanifest?v=4';if(!document.querySelector('meta[name="theme-color"]')){const m=document.createElement('meta');m.name='theme-color';m.content='#075a91';document.head.appendChild(m)}}
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(LOGO_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getLogo(){const d=await db();return new Promise(res=>{const r=d.transaction(STORE,'readonly').objectStore(STORE).get('logo');r.onsuccess=()=>res(r.result||null);r.onerror=()=>res(null)})}
async function setLogo(file){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(file,'logo');tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function delLogo(){const d=await db();return new Promise(res=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).delete('logo');tx.oncomplete=res})}
let logoURL='';async function renderLogo(){const img=document.getElementById('companyLogo'),empty=document.getElementById('logoEmpty'),f=await getLogo();if(!img||!empty)return;if(logoURL)URL.revokeObjectURL(logoURL);if(f){logoURL=URL.createObjectURL(f);img.src=logoURL;img.style.display='block';empty.style.display='none'}else{img.removeAttribute('src');img.style.display='none';empty.style.display='flex'}}
function installLogoUI(){const settings=[...document.querySelectorAll('.panel')].find(x=>x.textContent.includes('إعدادات النشاط'));if(!settings||document.getElementById('companyLogoPanel'))return;const box=document.createElement('div');box.id='companyLogoPanel';box.innerHTML=`<div style="display:flex;align-items:center;gap:14px;flex-wrap:wrap;margin-top:14px;padding-top:14px;border-top:1px solid #e4eaf0"><div id=logoEmpty style="width:72px;height:72px;border:2px dashed #b9c8d8;border-radius:16px;display:flex;align-items:center;justify-content:center;color:#789;font-size:12px;text-align:center">شعار<br>الشركة</div><img id=companyLogo alt="شعار الشركة" style="display:none;width:72px;height:72px;object-fit:contain;background:#fff;border:1px solid #dce5ee;border-radius:16px;padding:5px"><div style="flex:1;min-width:210px"><div class=n style="font-size:16px">شعار الشركة</div><div class=m>يظهر بجانب اسم النشاط ويحفظ على هذا الجهاز.</div><input id=companyLogoInput type=file accept="image/*" style="max-width:100%"><div class=pa><button class=blue id=saveCompanyLogo>رفع / استبدال الشعار</button><button class=del id=deleteCompanyLogo>حذف الشعار</button></div><div id=companyLogoMsg class=ok></div></div></div>`;settings.appendChild(box);document.getElementById('saveCompanyLogo').onclick=async()=>{const f=document.getElementById('companyLogoInput').files[0],m=document.getElementById('companyLogoMsg');if(!f||!f.type.startsWith('image/')){m.textContent='اختر صورة شعار أولًا.';return}await setLogo(f);document.getElementById('companyLogoInput').value='';await renderLogo();await renderHeaderLogo();m.textContent='تم حفظ شعار الشركة.'};document.getElementById('deleteCompanyLogo').onclick=async()=>{if(!confirm('حذف شعار الشركة؟'))return;await delLogo();await renderLogo();await renderHeaderLogo();document.getElementById('companyLogoMsg').textContent='تم حذف الشعار.'};renderLogo();renderHeaderLogo()}
async function renderHeaderLogo(){let img=document.getElementById('headerCompanyLogo'),head=document.querySelector('.h .w h2');if(!head)return;const f=await getLogo();if(!img){img=document.createElement('img');img.id='headerCompanyLogo';img.style.cssText='width:48px;height:48px;object-fit:contain;background:#fff;border-radius:12px;padding:3px;margin-left:10px;vertical-align:middle;display:none';head.prepend(img)}if(f){if(img.dataset.url)URL.revokeObjectURL(img.dataset.url);const u=URL.createObjectURL(f);img.dataset.url=u;img.src=u;img.style.display='inline-block'}else img.style.display='none'}
function installMobileAppNav(){if(document.getElementById('slbBottomNav'))return;const style=document.createElement('style');style.textContent=`@media(max-width:760px){body{padding-bottom:82px}.slb-screen-hidden{display:none!important}#slbBottomNav{position:fixed;bottom:0;left:0;right:0;z-index:9999;height:68px;background:#fff;border-top:1px solid #dce5ee;display:grid;grid-template-columns:repeat(4,1fr);box-shadow:0 -4px 18px rgba(0,0,0,.08);padding-bottom:env(safe-area-inset-bottom)}#slbBottomNav button{border:0;background:transparent;color:#607487;font:inherit;font-size:11px;font-weight:700;padding:7px 2px 5px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px}#slbBottomNav button span{font-size:22px;line-height:22px}#slbBottomNav button.active{color:#075a91;background:#eef7fc}.h{position:sticky!important;top:0;z-index:100;padding:10px 0!important;min-height:0!important}.h .w{padding-top:0!important;padding-bottom:0!important;min-height:0!important}.h h2,.h .w h2{font-size:20px!important;line-height:1.25!important;margin:0!important;padding:0!important;display:flex!important;align-items:center!important;gap:5px!important}.h .w>span,.h .w>div:not(#slbScreenTitle){font-size:13px!important;line-height:1.25!important;margin-top:3px!important;margin-bottom:0!important}#headerCompanyLogo{width:34px!important;height:34px!important;border-radius:9px!important;margin-left:6px!important}#slbScreenTitle{display:none!important}}@media(min-width:761px){#slbBottomNav,#slbScreenTitle{display:none!important}}`;document.head.appendChild(style);
 const nav=document.createElement('nav');nav.id='slbBottomNav';nav.setAttribute('aria-label','التنقل الرئيسي');nav.innerHTML=`<button data-screen="customers"><span>👥</span>العملاء</button><button data-screen="add"><span>➕</span>إضافة واستيراد</button><button data-screen="marketing"><span>📣</span>التسويق</button><button data-screen="settings"><span>⚙️</span>الإعدادات</button>`;document.body.appendChild(nav);
 let title=document.getElementById('slbScreenTitle');if(!title){title=document.createElement('div');title.id='slbScreenTitle';const wrap=document.querySelector('.w');if(wrap)wrap.prepend(title)}
 function classify(el){const t=(el.textContent||'').replace(/\s+/g,' ');if(el.querySelector('#l')||el.id==='l'||t.includes('قائمة العملاء')||t.includes('بحث')&&t.includes('العملاء'))return'customers';if(t.includes('إضافة عميل')||t.includes('استيراد')||t.includes('Excel'))return'add';if(t.includes('رسالة')||t.includes('صور المنتجات')||t.includes('مشاركة')||t.includes('واتساب')&&!t.includes('قائمة العملاء'))return'marketing';if(t.includes('إعدادات النشاط')||t.includes('تصدير')||t.includes('اسم النشاط')||el.querySelector('#companyLogoPanel'))return'settings';return'customers'}
 function candidates(){return[...document.querySelectorAll('body > .w > .panel, body > .w > .card, .w > .panel, .w > .card')].filter((x,i,a)=>a.indexOf(x)===i)}
 function show(screen){if(innerWidth>760)return;candidates().forEach(el=>el.classList.toggle('slb-screen-hidden',classify(el)!==screen));nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.screen===screen));title.textContent={customers:'العملاء',add:'إضافة واستيراد',marketing:'التسويق',settings:'الإعدادات'}[screen];sessionStorage.setItem('slbScreen',screen);scrollTo({top:0,behavior:'smooth'})}
 nav.onclick=e=>{const b=e.target.closest('button[data-screen]');if(b)show(b.dataset.screen)};const first=sessionStorage.getItem('slbScreen')||'customers';setTimeout(()=>show(first),150);new MutationObserver(()=>{if(innerWidth<=760){const s=sessionStorage.getItem('slbScreen')||'customers';candidates().forEach(el=>el.classList.toggle('slb-screen-hidden',classify(el)!==s))}}).observe(document.body,{childList:true,subtree:true});addEventListener('resize',()=>{if(innerWidth>760)candidates().forEach(el=>el.classList.remove('slb-screen-hidden'));else show(sessionStorage.getItem('slbScreen')||'customers')})}
function init(){installPWAHead();installLogoUI();installMobileAppNav();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=4').then(reg=>reg.update()).catch(console.error)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();