(function(){
const LOGO_DB='slbBrandDB',STORE='brand';
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(LOGO_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getLogo(){const d=await db();return new Promise(res=>{const r=d.transaction(STORE,'readonly').objectStore(STORE).get('logo');r.onsuccess=()=>res(r.result||null);r.onerror=()=>res(null)})}
async function setLogo(file){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(file,'logo');tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function delLogo(){const d=await db();return new Promise(res=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).delete('logo');tx.oncomplete=res})}
let logoURL='';async function renderLogo(){const img=document.getElementById('companyLogo'),empty=document.getElementById('logoEmpty'),f=await getLogo();if(logoURL)URL.revokeObjectURL(logoURL);if(f){logoURL=URL.createObjectURL(f);img.src=logoURL;img.style.display='block';empty.style.display='none'}else{img.removeAttribute('src');img.style.display='none';empty.style.display='flex'}}
function installLogoUI(){const settings=[...document.querySelectorAll('.panel')].find(x=>x.textContent.includes('إعدادات النشاط'));if(!settings||document.getElementById('companyLogoPanel'))return;const box=document.createElement('div');box.id='companyLogoPanel';box.innerHTML=`<div style="display:flex;align-items:center;gap:14px;flex-wrap:wrap;margin-top:14px;padding-top:14px;border-top:1px solid #e4eaf0"><div id=logoEmpty style="width:72px;height:72px;border:2px dashed #b9c8d8;border-radius:16px;display:flex;align-items:center;justify-content:center;color:#789;font-size:12px;text-align:center">شعار<br>الشركة</div><img id=companyLogo alt="شعار الشركة" style="display:none;width:72px;height:72px;object-fit:contain;background:#fff;border:1px solid #dce5ee;border-radius:16px;padding:5px"><div style="flex:1;min-width:210px"><div class=n style="font-size:16px">شعار الشركة</div><div class=m>يظهر بجانب اسم النشاط ويحفظ على هذا الجهاز.</div><input id=companyLogoInput type=file accept="image/*" style="max-width:100%"><div class=pa><button class=blue id=saveCompanyLogo>رفع / استبدال الشعار</button><button class=del id=deleteCompanyLogo>حذف الشعار</button></div><div id=companyLogoMsg class=ok></div></div></div>`;settings.appendChild(box);document.getElementById('saveCompanyLogo').onclick=async()=>{const f=document.getElementById('companyLogoInput').files[0],m=document.getElementById('companyLogoMsg');if(!f||!f.type.startsWith('image/')){m.textContent='اختر صورة شعار أولًا.';return}await setLogo(f);document.getElementById('companyLogoInput').value='';await renderLogo();await renderHeaderLogo();m.textContent='تم حفظ شعار الشركة.'};document.getElementById('deleteCompanyLogo').onclick=async()=>{if(!confirm('حذف شعار الشركة؟'))return;await delLogo();await renderLogo();await renderHeaderLogo();document.getElementById('companyLogoMsg').textContent='تم حذف الشعار.'};renderLogo();renderHeaderLogo()}
async function renderHeaderLogo(){let img=document.getElementById('headerCompanyLogo'),head=document.querySelector('.h .w h2');if(!head)return;const f=await getLogo();if(!img){img=document.createElement('img');img.id='headerCompanyLogo';img.style.cssText='width:48px;height:48px;object-fit:contain;background:#fff;border-radius:12px;padding:3px;margin-left:10px;vertical-align:middle;display:none';head.prepend(img)}if(f){if(img.dataset.url)URL.revokeObjectURL(img.dataset.url);const u=URL.createObjectURL(f);img.dataset.url=u;img.src=u;img.style.display='inline-block'}else img.style.display='none'}
function init(){installLogoUI();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=1').then(reg=>{reg.update();reg.addEventListener('updatefound',()=>{const w=reg.installing;if(w)w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller){const n=document.createElement('div');n.style.cssText='position:fixed;bottom:15px;left:15px;right:15px;z-index:99;background:#075a91;color:#fff;padding:12px;border-radius:12px;text-align:center;box-shadow:0 4px 20px #0004';n.innerHTML='يوجد تحديث جديد للتطبيق <button style="margin-right:8px;padding:7px 12px;border:0;border-radius:8px;font-weight:bold" id=reloadPWA>تحديث الآن</button>';document.body.appendChild(n);document.getElementById('reloadPWA').onclick=()=>location.reload()}})})}).catch(console.error)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();